
/*7)	Display the Id and Name of the Product ordered after “2021-10-05”. */

SELECT p.PRO_ID , PRO_NAME FROM CUSTOMER C 
INNER JOIN `ORDER` O ON C.CUS_ID= O.CUS_ID 
INNER JOIN SUPPLIER_PRICING S ON O.PRICING_ID=S.PRICING_ID
INNER JOIN PRODUCT AS P ON S.PRO_ID=P.PRO_ID
WHERE O.ORD_DATE>'2021-10-05';