/*4)	Display all the orders along with product name ordered by a customer having Customer_Id=2*/
SELECT ORD_ID ,ORD_AMOUNT,	ORD_DATE, o.CUS_ID,	o.PRICING_ID ,PRO_NAME FROM CUSTOMER C 
INNER JOIN `ORDER` O ON C.CUS_ID= O.CUS_ID 
INNER JOIN SUPPLIER_PRICING S ON O.PRICING_ID=S.PRICING_ID
INNER JOIN PRODUCT AS P ON S.PRO_ID=P.PRO_ID
WHERE C.CUS_ID=2;

